/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 563172
 */
public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
        LABELSalary.setVisible(false);
        LABELWageHr.setVisible(false);
        LABELHrWeek.setVisible(false);
        LABELWksYear.setVisible(false);
        FIELDSalary.setVisible(false);
        FIELDWageHr.setVisible(false);
        FIELDHrWeek.setVisible(false);
        FIELDWksYear.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TITLEAddANewEmployee = new javax.swing.JLabel();
        BUTTONHelp = new javax.swing.JButton();
        LABELEmpNum = new javax.swing.JLabel();
        LABELLastName = new javax.swing.JLabel();
        LABELFirstName = new javax.swing.JLabel();
        LABELGender = new javax.swing.JLabel();
        LABELLocation = new javax.swing.JLabel();
        LABELDeductRate = new javax.swing.JLabel();
        FIELDFirstName = new javax.swing.JTextField();
        FIELDEmpNum = new javax.swing.JTextField();
        FIELDLastName = new javax.swing.JTextField();
        FIELDGender = new javax.swing.JTextField();
        FIELDDeductRate = new javax.swing.JTextField();
        DROPDOWNLocation = new javax.swing.JComboBox<>();
        BUTTONFTE = new javax.swing.JButton();
        BUTTONSubmit = new javax.swing.JButton();
        BUTTONPTE = new javax.swing.JButton();
        FIELDSalary = new javax.swing.JTextField();
        LABELSalary = new javax.swing.JLabel();
        FIELDWageHr = new javax.swing.JTextField();
        LABELWageHr = new javax.swing.JLabel();
        FIELDHrWeek = new javax.swing.JTextField();
        LABELHrWeek = new javax.swing.JLabel();
        FIELDWksYear = new javax.swing.JTextField();
        LABELWksYear = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton2.setText("HELP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton3.setText("EXISTING");

        jButton4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton4.setText("VIEW MASTERLIST");

        jButton5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton5.setText("NEW");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5addNewEmp(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Welcome to the Employee Management System!");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 268, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)))
                .addGap(129, 129, 129))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(41, 41, 41)
                .addComponent(jButton4)
                .addGap(113, 113, 113))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TITLEAddANewEmployee.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TITLEAddANewEmployee.setText("Add A New Employee");

        BUTTONHelp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        BUTTONHelp.setText("HELP");
        BUTTONHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONHelpActionPerformed(evt);
            }
        });

        LABELEmpNum.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELEmpNum.setText("Employee Number");

        LABELLastName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELLastName.setText("Last Name");

        LABELFirstName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELFirstName.setText("First Name");

        LABELGender.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELGender.setText("Gender");

        LABELLocation.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELLocation.setText("Location");

        LABELDeductRate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELDeductRate.setText("Deduction Rate");

        FIELDFirstName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FIELDFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIELDFirstNameActionPerformed(evt);
            }
        });

        FIELDEmpNum.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FIELDEmpNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIELDEmpNumActionPerformed(evt);
            }
        });

        FIELDLastName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FIELDLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIELDLastNameActionPerformed(evt);
            }
        });

        FIELDGender.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FIELDGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIELDGenderActionPerformed(evt);
            }
        });

        FIELDDeductRate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FIELDDeductRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIELDDeductRateActionPerformed(evt);
            }
        });

        DROPDOWNLocation.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DROPDOWNLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mississauga", "Ottawa", "Chicago" }));
        DROPDOWNLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DROPDOWNLocationActionPerformed(evt);
            }
        });

        BUTTONFTE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BUTTONFTE.setText("FULL TIME");
        BUTTONFTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pressFTE(evt);
            }
        });
        BUTTONFTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONFTEActionPerformed(evt);
            }
        });

        BUTTONSubmit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BUTTONSubmit.setText("SUBMIT");
        BUTTONSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONSubmitActionPerformed(evt);
            }
        });

        BUTTONPTE.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BUTTONPTE.setText("PART TIME");
        BUTTONPTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClickPTE(evt);
            }
        });
        BUTTONPTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONPTEActionPerformed(evt);
            }
        });

        FIELDSalary.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FIELDSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIELDSalaryActionPerformed(evt);
            }
        });

        LABELSalary.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELSalary.setText("Salary");

        FIELDWageHr.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FIELDWageHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIELDWageHrActionPerformed(evt);
            }
        });

        LABELWageHr.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELWageHr.setText("Wage/Hr");

        FIELDHrWeek.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FIELDHrWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIELDHrWeekActionPerformed(evt);
            }
        });

        LABELHrWeek.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELHrWeek.setText("Hr/Week");

        FIELDWksYear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FIELDWksYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIELDWksYearActionPerformed(evt);
            }
        });

        LABELWksYear.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELWksYear.setText("Wks/Year");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LABELWksYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FIELDWksYear, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LABELHrWeek)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FIELDHrWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TITLEAddANewEmployee)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BUTTONFTE)
                            .addGap(52, 52, 52)
                            .addComponent(BUTTONPTE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LABELSalary)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FIELDSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(LABELWageHr)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FIELDWageHr, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BUTTONHelp)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BUTTONSubmit)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LABELEmpNum)
                                    .addComponent(LABELFirstName)
                                    .addComponent(LABELLastName)
                                    .addComponent(LABELLocation)
                                    .addComponent(LABELDeductRate)
                                    .addComponent(LABELGender))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FIELDDeductRate)
                                    .addComponent(FIELDGender)
                                    .addComponent(FIELDEmpNum)
                                    .addComponent(FIELDFirstName)
                                    .addComponent(FIELDLastName)
                                    .addComponent(DROPDOWNLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(88, 88, 88))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BUTTONHelp)
                    .addComponent(TITLEAddANewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BUTTONFTE)
                    .addComponent(BUTTONPTE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABELEmpNum)
                            .addComponent(FIELDEmpNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABELFirstName)
                            .addComponent(FIELDFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABELLastName)
                            .addComponent(FIELDLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LABELSalary)
                                .addComponent(FIELDSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FIELDGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABELGender)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LABELWageHr)
                                .addComponent(FIELDWageHr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABELLocation)
                            .addComponent(DROPDOWNLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LABELHrWeek)
                                .addComponent(FIELDHrWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABELDeductRate)
                            .addComponent(FIELDDeductRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LABELWksYear)
                                .addComponent(FIELDWksYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30)
                .addComponent(BUTTONSubmit)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5addNewEmp(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5addNewEmp
        // TODO add your handling code here:
        Add Add = new Add();
        Add.setVisible(true);
    }//GEN-LAST:event_jButton5addNewEmp

    private void BUTTONHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTONHelpActionPerformed

    private void FIELDFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIELDFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIELDFirstNameActionPerformed

    private void FIELDEmpNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIELDEmpNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIELDEmpNumActionPerformed

    private void FIELDLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIELDLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIELDLastNameActionPerformed

    private void FIELDGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIELDGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIELDGenderActionPerformed

    private void FIELDDeductRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIELDDeductRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIELDDeductRateActionPerformed

    private void DROPDOWNLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DROPDOWNLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DROPDOWNLocationActionPerformed

    private void BUTTONFTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONFTEActionPerformed
        // TODO add your handling code here:
        LABELSalary.setVisible(true);
        FIELDSalary.setVisible(true);
        LABELWageHr.setVisible(false);
        LABELHrWeek.setVisible(false);
        LABELWksYear.setVisible(false);
        FIELDWageHr.setVisible(false);
        FIELDHrWeek.setVisible(false);
        FIELDWksYear.setVisible(false);
    }//GEN-LAST:event_BUTTONFTEActionPerformed

    private void BUTTONSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTONSubmitActionPerformed

    private void BUTTONPTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONPTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTONPTEActionPerformed

    private void FIELDSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIELDSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIELDSalaryActionPerformed

    private void pressFTE(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pressFTE
        // TODO add your handling code here:
    }//GEN-LAST:event_pressFTE

    private void FIELDWageHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIELDWageHrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIELDWageHrActionPerformed

    private void FIELDHrWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIELDHrWeekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIELDHrWeekActionPerformed

    private void FIELDWksYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIELDWksYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIELDWksYearActionPerformed

    private void ClickPTE(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickPTE
        // TODO add your handling code here:
        LABELWageHr.setVisible(true);
        LABELHrWeek.setVisible(true);
        LABELWksYear.setVisible(true);
        FIELDWageHr.setVisible(true);
        FIELDHrWeek.setVisible(true);
        FIELDWksYear.setVisible(true);
        LABELSalary.setVisible(false);
        FIELDSalary.setVisible(false);
    }//GEN-LAST:event_ClickPTE

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTONFTE;
    private javax.swing.JButton BUTTONHelp;
    private javax.swing.JButton BUTTONPTE;
    private javax.swing.JButton BUTTONSubmit;
    private javax.swing.JComboBox<String> DROPDOWNLocation;
    private javax.swing.JTextField FIELDDeductRate;
    private javax.swing.JTextField FIELDEmpNum;
    private javax.swing.JTextField FIELDFirstName;
    private javax.swing.JTextField FIELDGender;
    private javax.swing.JTextField FIELDHrWeek;
    private javax.swing.JTextField FIELDLastName;
    private javax.swing.JTextField FIELDSalary;
    private javax.swing.JTextField FIELDWageHr;
    private javax.swing.JTextField FIELDWksYear;
    private javax.swing.JLabel LABELDeductRate;
    private javax.swing.JLabel LABELEmpNum;
    private javax.swing.JLabel LABELFirstName;
    private javax.swing.JLabel LABELGender;
    private javax.swing.JLabel LABELHrWeek;
    private javax.swing.JLabel LABELLastName;
    private javax.swing.JLabel LABELLocation;
    private javax.swing.JLabel LABELSalary;
    private javax.swing.JLabel LABELWageHr;
    private javax.swing.JLabel LABELWksYear;
    private javax.swing.JLabel TITLEAddANewEmployee;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
