/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 563172
 */
public class Existing extends javax.swing.JFrame {

    /**
     * Creates new form Existing
     */
    public Existing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITLEExistingEmployee = new javax.swing.JLabel();
        LABELEmpNum = new javax.swing.JLabel();
        FIELDEmpNum = new javax.swing.JTextField();
        BUTTONCheck = new javax.swing.JButton();
        LABELYes = new javax.swing.JLabel();
        LABELNo = new javax.swing.JLabel();
        BUTTONCheck1 = new javax.swing.JButton();
        BUTTONCheck2 = new javax.swing.JButton();
        BUTTONCheck3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TITLEExistingEmployee.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TITLEExistingEmployee.setText("Existing Employee");

        LABELEmpNum.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELEmpNum.setText("Employee Number");

        FIELDEmpNum.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        BUTTONCheck.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BUTTONCheck.setText("CHECK");
        BUTTONCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONCheckActionPerformed(evt);
            }
        });

        LABELYes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELYes.setText("Yes, this employee number is in the system");

        LABELNo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LABELNo.setText("No, this employee number is not in the system");

        BUTTONCheck1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BUTTONCheck1.setText("VIEW");
        BUTTONCheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONCheck1ActionPerformed(evt);
            }
        });

        BUTTONCheck2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BUTTONCheck2.setText("EDIT");
        BUTTONCheck2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONCheck2ActionPerformed(evt);
            }
        });

        BUTTONCheck3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BUTTONCheck3.setText("REMOVE");
        BUTTONCheck3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pressRemove(evt);
            }
        });
        BUTTONCheck3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONCheck3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BUTTONCheck1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LABELYes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LABELEmpNum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                        .addComponent(FIELDEmpNum, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TITLEExistingEmployee))
                                .addGap(60, 60, 60)
                                .addComponent(BUTTONCheck))
                            .addComponent(LABELNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(297, 297, 297))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BUTTONCheck3)
                            .addComponent(BUTTONCheck2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(TITLEExistingEmployee)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABELEmpNum)
                    .addComponent(FIELDEmpNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUTTONCheck))
                .addGap(31, 31, 31)
                .addComponent(LABELYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELNo)
                .addGap(57, 57, 57)
                .addComponent(BUTTONCheck1)
                .addGap(18, 18, 18)
                .addComponent(BUTTONCheck2)
                .addGap(18, 18, 18)
                .addComponent(BUTTONCheck3)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTONCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTONCheckActionPerformed

    private void BUTTONCheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONCheck1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTONCheck1ActionPerformed

    private void BUTTONCheck2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONCheck2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTONCheck2ActionPerformed

    private void BUTTONCheck3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONCheck3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTONCheck3ActionPerformed

    private void pressRemove(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pressRemove
        // TODO add your handling code here:
        RemoveConfirm RemoveConfirm = new RemoveConfirm();
        RemoveConfirm.setVisible(true);
    }//GEN-LAST:event_pressRemove

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Existing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Existing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Existing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Existing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Existing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTONCheck;
    private javax.swing.JButton BUTTONCheck1;
    private javax.swing.JButton BUTTONCheck2;
    private javax.swing.JButton BUTTONCheck3;
    private javax.swing.JTextField FIELDEmpNum;
    private javax.swing.JLabel LABELEmpNum;
    private javax.swing.JLabel LABELNo;
    private javax.swing.JLabel LABELYes;
    private javax.swing.JLabel TITLEExistingEmployee;
    // End of variables declaration//GEN-END:variables
}
